### ISSUE TITLE
new  proxy 

### ISSUE THREAD

**Issue by chenjia404** [zolagonano/awesome-zeronet#3]
https://zeronet.ipfsscan.io

**Comment by zolagonano** [comment]
Hi, thanks for contributing :)
But the proxy seems to be down at the moment, if it's temporary let me know to added to the list

**Comment by chenjia404** [comment]
> Hi, thanks for contributing :) But the proxy seems to be down at the moment, if it's temporary let me know to added to the list

i fix it now

**Comment by zolagonano** [comment]
thanks, added it
